version: '2'
services:
  postgres:
    container_name: ativ2-postgres-cliente
    image: natarajan/db-cliente
    build: ./postgres
    ports:
     - "5434:5432"
    expose:
     - 5434
    volumes:
     - postgres-volume-cliente:/var/lib/postgresql/data/
  web:
    container_name: ativ2-app-cliente
    build: .
    image: natarajan/cliente
    ports:
     - "8081:8080"
     - "4949:4848"
    links:
     - "postgres:banco-cliente"
networks:
  default:
    external:
      name: cliente_default_ntw
volumes:
    postgres-volume-cliente:
      driver: local
